export const UGANDAN_CROPS = [
  'Coffee',
  'Tea',
  'Cotton',
  'Tobacco',
  'Maize',
  'Beans',
  'Cassava',
  'Sweet Potatoes',
  'Matooke (Cooking Bananas)',
  'Irish Potatoes',
  'Rice',
  'Millet',
  'Sorghum',
  'Groundnuts (Peanuts)',
  'Soybeans',
  'Sugarcane',
  'Sunflower',
  'Wheat',
  'Cowpeas',
  'Sesame (Simsim)',
  'Pineapples',
  'Passion Fruits',
  'Mangoes',
  'Avocados',
  'Jackfruit',
  'Papaya',
  'Tomatoes',
  'Onions',
  'Cabbage',
  'Carrots',
  'Eggplant',
  'Green Peppers',
  'Vanilla',
  'Cocoa'
].sort()

// Export as both named exports for convenience
export const ugandanCrops = UGANDAN_CROPS